GCP Disk Autodelete and Bazel clean before grakn Build in execute.sh (#316)
## What is the goal of this PR?
Benchmark builds are failing due the following error:
```
INFO: Analyzed target //:assemble-linux-targz (508 packages loaded, 2798 targets configured).
INFO: Found 1 target...
ERROR: missing input file '@local_jdk//:jre/lib/amd64/server/classes.jsa'
ERROR: /home/ubuntu/.cache/bazel/_bazel_ubuntu/490c8da38bc09af05d455a845f491ad6/external/bazel_tools/tools/jdk/BUILD:306:1: @bazel_tools//tools/jdk:platformclasspath: missing input file '@local_jdk//:jre/lib/amd64/server/classes.jsa'
ERROR: /home/ubuntu/.cache/bazel/_bazel_ubuntu/490c8da38bc09af05d455a845f491ad6/external/bazel_tools/tools/jdk/BUILD:306:1 1 input file(s) do not exist
INFO: Elapsed time: 56.512s, Critical Path: 0.05s
```

To protect against this we add steps like bazel cleans, set JAVA_HOME, and also make sure disks are deleted and recreated on every GCP instance creation to avoid stale bazel caches which is suspected to be one of the sources of this error.

## What are the changes implemented in this PR?
* Add sleep, bazel clean, and JAVA_HOME in `execute.sh`
* Set disk autodelete to be true